#!/usr/bin/env python3
"""Exact affine restrictions of Hemera's partial layer; NOT a sponge attack.

Python 3 + SymPy (used by inverse_sbox.chain import). No search or randomness:
force every active S-box input to 1, solve the resulting linear constraints.
The same construction works for x^7 because both S-boxes fix 1.
"""
import hashlib
import json
import re
import argparse

from inverse_sbox import P, ROOT, chain


def dot(a, b):
    return sum(x*y for x, y in zip(a, b)) % P


def mv(a, v):
    return [dot(row, v) for row in a]


def mm(a, b):
    return [[dot(row, col) for col in zip(*b)] for row in a]


def affine_solve(rows, rhs):
    a = [row[:] + [r] for row, r in zip(rows, rhs)]
    pivots = []
    for col in range(16):
        r = len(pivots)
        pivot = next((i for i in range(r, len(a)) if a[i][col]), None)
        if pivot is None:
            continue
        a[r], a[pivot] = a[pivot], a[r]
        scale = pow(a[r][col], -1, P)
        a[r] = [x*scale % P for x in a[r]]
        for i in range(len(a)):
            if i != r:
                scale = a[i][col]
                a[i] = [(x-scale*y) % P for x, y in zip(a[i], a[r])]
        pivots.append(col)
    assert all(any(row[:16]) or row[16] == 0 for row in a)
    base = [0]*16
    for i, col in enumerate(pivots):
        base[col] = a[i][16]
    basis = []
    for free in sorted(set(range(16))-set(pivots)):
        v = [int(i == free) for i in range(16)]
        for i, col in enumerate(pivots):
            v[col] = -a[i][free] % P
        basis.append(v)
    assert mv(rows, base) == rhs
    assert all(mv(rows, v) == [0]*len(rows) for v in basis)
    return base, basis


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-rust-fixture", action="store_true")
    args = parser.parse_args()
    paths = ["rs/src/field.rs", "rs/src/constants.rs", "rs/src/permutation.rs"]
    source, constants, _ = [(ROOT / p).read_text() for p in paths]
    block = source.split("pub const MATRIX_DIAG_16:", 1)[1].split("];", 1)[0]
    diag = [int(x, 16) for x in re.findall(r"Goldilocks::new\((0x[0-9a-fA-F]+)\)", block)]
    block = constants.split("pub const ROUND_CONSTANTS_U64:", 1)[1].split("];", 1)[0]
    rc = [int(x, 16) for x in re.findall(r"0x[0-9a-fA-F]+", block)]
    assert len(diag) == 16 and len(rc) == 144
    rc = rc[128:]
    m = [[(1+(diag[i] if i == j else 0)) % P for j in range(16)] for i in range(16)]
    a = [[int(i == j) for j in range(16)] for i in range(16)]
    b, rows, rhs, results = [0]*16, [], [], []
    for k, c in enumerate(rc, 1):
        rows.append(a[0][:])
        rhs.append((1-b[0]-c) % P)
        b[0] = (b[0]+c) % P
        a, b = mm(m, a), mv(m, b)
        base, basis = affine_solve(rows, rhs)
        assert len(basis) == 16-k
        # Exact linear certificates above establish the whole affine space.
        # These concrete executions additionally guard the implemented model.
        for z in [0, 1, 2, P-1, 0x123456789abcdef]:
            direction = basis[0] if basis else [0]*16
            state = [(x+z*y) % P for x, y in zip(base, direction)]
            expected = [(x+y) % P for x, y in zip(mv(a, state), b)]
            for c0 in rc[:k]:
                state[0] = (state[0]+c0) % P
                assert state[0] == 1
                state[0] = pow(state[0], P-2, P)
                state = mv(m, state)
            assert state == expected
        results.append({"partial_rounds": k, "dimension": len(basis),
                        "base": base, "basis": basis,
                        "output_base": [(x+y) % P for x, y in zip(mv(a, base), b)],
                        "output_basis": [mv(a, v) for v in basis]})
    if args.write_rust_fixture:
        certificate = results[14]
        fixture = "// Generated by research/partial_subspace.py --write-rust-fixture.\n"
        for name, values in [("BASE", certificate["base"]),
                             ("DIRECTION", certificate["basis"][0]),
                             ("OUTPUT_BASE", certificate["output_base"]),
                             ("OUTPUT_DIRECTION", certificate["output_basis"][0])]:
            fixture += f"const {name}: [u64; 16] = [\n"
            fixture += "".join(f"    {n},\n" for n in values) + "];\n"
        (ROOT / "rs/tests/fixtures/partial_subspace.rs").write_text(fixture)
    inv_cost = chain(source)["multiplications"]
    costs = []
    for name, rp, native, quadratic in [("inverse16", 16, inv_cost, 3),
                                       ("power7_16_control", 16, 4, 4),
                                       ("power7_22_reference_round_count", 22, 4, 4)]:
        costs.append({"candidate": name, "full_rounds": 8, "partial_rounds": rp,
                      "native_nonlinear_muls": 8*16*4+rp*native,
                      "native_muls_with_current_internal_diagonal": 8*16*4+rp*(native+16),
                      "quadratic_nonlinear_constraints": 8*16*4+rp*quadratic})
    print(json.dumps({
        "scope": "partial-layer affine certificates; NOT a full-round attack or security bound",
        "p": P,
        "sources_sha256": {p: hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in paths},
        "fixed_sbox_input": 1,
        "dimensions": [{"partial_rounds": r["partial_rounds"], "dimension": r["dimension"]} for r in results],
        "restrictions": results[-2:],
        "cost_model": "squares count as muls; x7 four muls; inverse three quadratic equations; excludes additions, witness generation, proof backend costs",
        "costs": costs,
    }, indent=2))


if __name__ == "__main__":
    main()
